const word_list = {
  "a": ['also', 'area', 'away', 'able', 'arts', 'auto'],
  "b": ['been', 'back', 'best', 'book', 'both', 'blog', 'body', 'blue', 'baby', 'bill', 'bank'],
  "c": ['city', 'code', 'case', 'care', 'call', 'card', 'cost', 'come', 'cart', 'club', 'cell', 'cars', 'chat'],
  "d": ['date', 'data', 'does', 'days', 'down', 'done', 'dour', 'door'],
  "e": ['each', 'even', 'east', 'easy', 'ever', 'else', 'edit'],
  "f": ['from', 'free', 'find', 'full', 'file', 'form', 'food', 'four', 'film', 'five', 'fast', 'fact', 'feel', 'fire'],
  "g": ['good', 'game', 'give', 'gift', 'gold', 'girl', 'golf'],
  "h": ['have', 'home', 'here', 'help', 'high', 'hard', 'hand', 'head', 'half'],
  "i": ['into', 'info', 'item'],
  "j": ['just', 'john', 'jobs', 'join', 'june', 'july'],
  "k": ['know', 'keep', 'kids'],
  "l": ['like', 'list', 'last', 'life', 'line', 'long', 'link', 'love', 'look', 'left', 'live', 'less', 'land', 'loan', 'lake', 'loss'],
  "m": ['more', 'most', 'make', 'many', 'mail', 'must', 'made', 'much', 'main', 'mark', 'meet'],
  "n": ['news', 'name', 'next', 'need', 'note', 'nude', 'none'],
  "o": ['only', 'over', 'open', 'once'],
  "p": ['page', 'post', 'part', 'plan', 'play', 'park', 'porn', 'past', 'plus'],
  "r": ['read', 'real', 'rate', 'room', 'road', 'rock', 'risk'],
  "s": ['site', 'some', 'such', 'said', 'send', 'show', 'sign', 'same', 'size', 'shop', 'save', 'sale', 'side', 'sell', 'star', 'self', 'sure', 'says', 'sort', 'step', 'sour', 'spur', 'spun', 'spin'],
  "t": ['this', 'time', 'they', 'than', 'them', 'then', 'type', 'take', 'text', 'teen', 'team', 'test', 'term', 'tell', 'talk', 'true', 'tips', 'tech', 'town', 'toys'],
  "u": ['used', 'user', 'upon', 'unit'],
  "v": ['view', 'very'],
  "w": ['with', 'will', 'what', 'when', 'were', 'work', 'well', 'want', 'west', 'week', 'word', 'wide'],
  "y": ['your', 'year', 'york'],
};